# Update the data sha
old = setwd("../pct-data/")
system("git pull")
mes_add = paste0("git add ", region, "/*")
system(mes_add)
mes_commit = paste0("git commit -m 'Add interegional new data for ", region, "'")
system(mes_commit)
system("git push origin master")
(newsha = system("git rev-parse --short HEAD", intern = T))
setwd("../pct-shiny/")
system("git pull")
writeLines(newsha, "data_sha")
system(paste0("git commit -am 'Update interegional data for ", region, "'"))
system("git push origin master")
setwd(old)